title : Opravicujemo.se
tagline: Opravičujemo se za vse nevšečnosti
description: Opravičujemo se za vse nevšečnosti je podkast o življenju, vesolju in sploh vsem ... v katerem po nekem čudnem naključju vsako epizodo obdelamo eno poglavje kultne trilogije v petih delih Štoparski vodnik po Galaksiji, ki jo je napisal Douglas Adams. Še veš kje imaš brisačo? 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://opravicujemo.se" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: opravicujemose
google_analytics: UA-686717-20
author: "Davorin Pavlica"
twitter_username: "davorinpavlica"
plugins: [jekyll-paginate]
paginate: 10
paginate_path: /page:num/

plugins:
  - jekyll-redirect-from