title : Opravicujemo.se
tagline: Opravičujemo se za vse nevšečnosti
description: Podkast o knjigi, ki jo poznajo le redki prebivalci tega nepomembnega modro-zelenega planeta. Bolj natančno o petih knjigah, ki govorijo o prej omenjeni knjigi. Avtorji se že vnaprej opravičujemo za vse nevšečnosti, ki bi morda lahko nastale ob in po poslušanju tega podkasta. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: opravicujemose
